# -*- coding: utf-8 -*-
"""Copy of Python lib assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5Ez0q-m3oKCIB3anjR0sFH5RdJXARFF

Note: 

* Before writing any code remember that this assigment is for helping you to get familiar with the python libraries we frequently use 

* This project is designed to have a work flow such that everyone is in same page for this purpose the variables are
given a strict name which should not be changed or modified according to your convinience

* Few of new functions like .head() .xticks().... and concepts may have been introduced in the assingment, so we encourage you
all to go through them without skipping.

* You will be using Pandas,Numpy,Matplotlib in this assignment, so if you're not familiar with some functions, you may refer their documentations

Task:


*   Your given a dataset **countries-aggregated.csv**file which contains the daily data of global covid confirmed,recovered and death cases.
*   Your task is to process the data extract the required information form it and visualise the data using the python libraries you learnt in this week
"""

#Import necessary libraries
import pandas as pd
import io

from google.colab import files
uploaded = files.upload()

#read countries-aggregated.csv file from provided dataset into a df_world named variable
'''
link for csv file

https://drive.google.com/file/d/1BN0Bi7EO7F3ZGy3HIbpSN9zH31cxTmqk/view?usp=sharing

'''
#Note: Proper file directory should be provided
'''************************Your code here**********************'''
df_world = pd.read_csv(io.BytesIO(uploaded['countries-aggregated.csv']))
print(df_world)

#Display first five data points
 print(df_world.head(5))

"""Task 1:


1.   Get the data of 20 most affected countries by covid 19
2.   Plot a bar plot showing Confirmed,Recovered and Deaths for these 20 countries


"""

''' 
    
  Obtain total number of confirmed,recovered and deaths for each country registered upto 2021-04-09 and store it in df_country
    
    
  '''
 
  '''************************Your code here**********************'''


df_country= df_world[df_world['Date']=='2021-04-09']#[['Date', 'Country', 'Confirmed', 'Recovered','Deaths']]
print(df_country)

#Display first five data points

dffdp = df_world[df_world['Date']=='2021-01-01']
print(dffdp.head(5))

#Obtain top 20 affected countries and store them in top_20

'''************************Your code here**********************'''
latest = df_world[df_world['Date']=='2021-04-09']
top_20 = latest.sort_values(by='Confirmed', ascending=False)[:20]

print(top_20)

#bar plot
import numpy as np
import matplotlib.pyplot as plt
width = 0.15
# plt.bar(top_20['Country'],top_20['Confirmed'], width = width, edgecolor ='blue')
# plt.bar(top_20['Country'],top_20['Recovered'], width = width, edgecolor ='orange')
# plt.bar(top_20['Country'],top_20['Deaths'], width = width, edgecolor ='green')
tot = len(top_20['Country'])
conf = top_20['Confirmed']
rec = top_20['Recovered']
death = top_20['Deaths']
total = np.arange(tot)
plt.bar(total,conf,width=width,label="Confirmed")
plt.bar(total+width,rec,width=width,label="Recovered")
plt.bar(total+width*2,death,width=width,label="Deaths")

plt.xlabel('Country')
plt.xticks(total+width, top_20['Country'],rotation=90)
plt.legend()

"""Task 2:

1.     Your task is now to visualize the Covid spread in India from day 1 to present day using matplotlib library



"""

#Get the daily number of confirmed,death and recovered cases of India from df_world
'''************************Your code here**********************'''
df_india= df_world[df_world['Country']=='India']

print(df_india)

'''Visualising
************************
As we just need a basic idea of how the trajectory of rise of covid cases in india we need not require these many data points so take a 
data point from each month and use for plotting below graphs

Plot a graph with title 'Covid 19 Projection India' for Date(x-axis) vs Confirmed(y-axis)

give x label 'Date'
give y label 'Number of Confirmed Cases'

'''

#Get data point from each month and store in df_monthly
df_monthly=df_india['Confirmed'][::30]
months = df_india['Date'][::30]

#graph
plt.plot(months,df_monthly)

#x-axis labels 
plt.xlabel('Date')
#y-axis labels 
plt.ylabel('Number of Confirmed Cases')
#plot title 
plt.title('Covid 19 Projection India')
#save plot 

#display 
plt.show()

''' We get a Simple Plot on the execution of above code which looks like this where X-axis has Dates and Y-axis has Number of Confirmed cases. 
But this is not the best representation for large dataset values along the axes as you can see the ‘Dates’ are overlapping on X-axis.
For this we use xticks() function go through about this and comment what it does'''

#graph
plt.plot(months,df_monthly)

#x-axis labels 
plt.xlabel('Date')
#y-axis labels 
plt.ylabel('Number of Confirmed Cases')
#plot title 
plt.title('Covid 19 Projection India')
#xticks 
plt.xticks(rotation = 75)

#plot
plt.show()

